#  ClusterRole avec permissions étendues
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-monitoring
rules:
# Permissions pour les pods dans tous les namespaces
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]

# Permissions pour la surveillance des nodes
- apiGroups: [""]
  resources: ["nodes", "nodes/status"]
  verbs: ["get", "list", "watch"]

# Permissions pour les deployments
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Permissions pour les services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create"]

# Permissions pour les événements
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]

# Permissions pour les configmaps et secrets
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

# Permissions pour les namespaces
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]